import Foundation
import SystemConfiguration

@_cdecl("sc_schema_copy_catalog")
public func sc_schema_copy_catalog() -> UnsafeMutableRawPointer? {
    let payload: [String: Any] = [
        "reserved": [
            "link": kSCResvLink as String,
            "inactive": kSCResvInactive as String,
        ],
        "preferences": [
            "current_set": kSCPrefCurrentSet as String,
            "network_services": kSCPrefNetworkServices as String,
            "sets": kSCPrefSets as String,
            "system": kSCPrefSystem as String,
        ],
        "components": [
            "network": kSCCompNetwork as String,
            "service": kSCCompService as String,
            "global": kSCCompGlobal as String,
            "host_names": kSCCompHostNames as String,
            "interface": kSCCompInterface as String,
            "system": kSCCompSystem as String,
            "users": kSCCompUsers as String,
            "any_regex": kSCCompAnyRegex as String,
        ],
        "entities": [
            "airport": kSCEntNetAirPort as String,
            "dhcp": kSCEntNetDHCP as String,
            "dns": kSCEntNetDNS as String,
            "ethernet": kSCEntNetEthernet as String,
            "interface": kSCEntNetInterface as String,
            "ipsec": kSCEntNetIPSec as String,
            "ipv4": kSCEntNetIPv4 as String,
            "ipv6": kSCEntNetIPv6 as String,
            "l2tp": kSCEntNetL2TP as String,
            "link": kSCEntNetLink as String,
            "modem": kSCEntNetModem as String,
            "ppp": kSCEntNetPPP as String,
            "pppoe": kSCEntNetPPPoE as String,
            "pptp": kSCEntNetPPTP as String,
            "proxies": kSCEntNetProxies as String,
            "smb": kSCEntNetSMB as String,
            "six_to_four": kSCEntNet6to4 as String,
        ],
        "generic_properties": [
            "interface_name": kSCPropInterfaceName as String,
            "mac_address": kSCPropMACAddress as String,
            "user_defined_name": kSCPropUserDefinedName as String,
            "version": kSCPropVersion as String,
        ],
        "ipv4": [
            "addresses": kSCPropNetIPv4Addresses as String,
            "config_method": kSCPropNetIPv4ConfigMethod as String,
            "dhcp_client_id": kSCPropNetIPv4DHCPClientID as String,
            "router": kSCPropNetIPv4Router as String,
            "subnet_masks": kSCPropNetIPv4SubnetMasks as String,
            "automatic": kSCValNetIPv4ConfigMethodAutomatic as String,
            "bootp": kSCValNetIPv4ConfigMethodBOOTP as String,
            "dhcp": kSCValNetIPv4ConfigMethodDHCP as String,
            "inform": kSCValNetIPv4ConfigMethodINFORM as String,
            "link_local": kSCValNetIPv4ConfigMethodLinkLocal as String,
            "manual": kSCValNetIPv4ConfigMethodManual as String,
            "ppp": kSCValNetIPv4ConfigMethodPPP as String,
        ],
        "ipv6": [
            "addresses": kSCPropNetIPv6Addresses as String,
            "config_method": kSCPropNetIPv6ConfigMethod as String,
            "router": kSCPropNetIPv6Router as String,
            "automatic": kSCValNetIPv6ConfigMethodAutomatic as String,
            "link_local": kSCValNetIPv6ConfigMethodLinkLocal as String,
            "manual": kSCValNetIPv6ConfigMethodManual as String,
            "router_advertisement": kSCValNetIPv6ConfigMethodRouterAdvertisement as String,
            "six_to_four": kSCValNetIPv6ConfigMethod6to4 as String,
        ],
        "dns": [
            "domain_name": kSCPropNetDNSDomainName as String,
            "options": kSCPropNetDNSOptions as String,
            "search_domains": kSCPropNetDNSSearchDomains as String,
            "server_addresses": kSCPropNetDNSServerAddresses as String,
            "server_port": kSCPropNetDNSServerPort as String,
        ],
        "proxies": [
            "exceptions_list": kSCPropNetProxiesExceptionsList as String,
            "http_enable": kSCPropNetProxiesHTTPEnable as String,
            "http_proxy": kSCPropNetProxiesHTTPProxy as String,
            "http_port": kSCPropNetProxiesHTTPPort as String,
            "https_enable": kSCPropNetProxiesHTTPSEnable as String,
            "https_proxy": kSCPropNetProxiesHTTPSProxy as String,
            "https_port": kSCPropNetProxiesHTTPSPort as String,
            "socks_enable": kSCPropNetProxiesSOCKSEnable as String,
            "socks_proxy": kSCPropNetProxiesSOCKSProxy as String,
            "socks_port": kSCPropNetProxiesSOCKSPort as String,
        ],
        "interface_types": [
            "ethernet": kSCValNetInterfaceTypeEthernet as String,
            "firewire": kSCValNetInterfaceTypeFireWire as String,
            "ppp": kSCValNetInterfaceTypePPP as String,
            "six_to_four": kSCValNetInterfaceType6to4 as String,
            "ipsec": kSCValNetInterfaceTypeIPSec as String,
            "pppoe": kSCValNetInterfaceSubTypePPPoE as String,
            "ppp_serial": kSCValNetInterfaceSubTypePPPSerial as String,
            "pptp": kSCValNetInterfaceSubTypePPTP as String,
            "l2tp": kSCValNetInterfaceSubTypeL2TP as String,
        ],
    ]

    return boxString(jsonString(from: payload))
}
